"""create_prescriptions_table

Revision ID: e1958b089da1
Revises: f29befa3f21a
Create Date: 2026-05-30 16:51:11.500330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1958b089da1'
down_revision: Union[str, None] = 'f29befa3f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False, comment='Original filename provided by the client — never used for storage.'),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False, comment='UUID-based filename written to disk.'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Relative path from project root to the stored file.'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='Canonical lowercase extension: pdf | jpg | jpeg | png.'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='File size in bytes.'),
    sa.Column('symptoms', sa.Text(), nullable=True, comment='Free-text symptoms / health notes from the user.'),
    sa.Column('upload_status', sa.String(length=30), server_default='uploaded', nullable=False, comment='uploaded | processing | processed | failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prescriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions')),
    sa.UniqueConstraint('stored_file_name', name=op.f('uq_prescriptions_stored_file_name'))
    )
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###

